### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Tom-cy** [ismile/kola#17]
我正在学习koa ，我了解一点typescript 和node 然后看了你的这个kola ，表示没有看懂,  https://github.com/Tom-cy/book_node/tree/master/node 这个是我用express + mongodb 写的， 想用koa 进行重构，当然也想用typescript , 能不能有一个简单版的，让我学习学习

**Comment by ismile** [comment]
it will be more easier for us if you could communicate with english.

seem u have done express before, so learning koa will be more easier for u, it has nearly same api, it just koa has separate router that called `koa-router`

here the simplest koa app 

```
const Koa = require('koa')
const Router = require('koa-router')

const app = new Koa()
const router = new Router()

router.get('/', (ctx, next) => {
  ctx.body = {
    hello: 'WORLD'
  }
});
  
app
  .use(router.routes())
  .use(router.allowedMethods());

app.listen(3000, '127.0.0.1')
console.info('[APP] Server listening on 127.0.0.1:3000')
```
